# Generated by Django 4.2.16 on 2024-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('InProgress', 'InProgress'), ('Lost', 'Lost'), ('Won', 'Won')],
                                           default='InProgress', max_length=10)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('max_incorrect_guesses', models.IntegerField()),
                ('guessed_letters', models.TextField(default='')),
            ],
        ),
    ]
